#!/usr/bin/env bash
#
# Synthesize the CMakeLists.txt for one analyzer/KB compile job.
# Mirrors src/compile.ts:generateCompileCMakeLists in the vscode-nlp
# extension, with includes/libs pointed at the unpacked
# nlpengine-compile-libs-<platform>.zip from the engine release.
#
# Usage:
#   bash scripts/emit-cmake.sh \
#     --anapath      <dir>    # contains run/*.cpp, kb/*.cpp, StdAfx.h
#     --engine-libs  <dir>    # unpacked nlpengine-compile-libs-<platform>.zip
#     --analyzer     <name>   # base name for the output shared lib
#     --kb-only      true|false
#
# Writes <anapath>/CMakeLists.txt.

set -euo pipefail

ANAPATH=""
ENGINE_LIBS=""
ANALYZER=""
KB_ONLY="false"

while [ $# -gt 0 ]; do
  case "$1" in
    --anapath)      ANAPATH="$2"; shift 2 ;;
    --engine-libs)  ENGINE_LIBS="$2"; shift 2 ;;
    --analyzer)     ANALYZER="$2"; shift 2 ;;
    --kb-only)      KB_ONLY="$2"; shift 2 ;;
    *) echo "emit-cmake.sh: unknown arg: $1" >&2; exit 2 ;;
  esac
done

[ -n "$ANAPATH" ]     || { echo "emit-cmake.sh: --anapath required" >&2; exit 2; }
[ -n "$ENGINE_LIBS" ] || { echo "emit-cmake.sh: --engine-libs required" >&2; exit 2; }
[ -n "$ANALYZER" ]    || { echo "emit-cmake.sh: --analyzer required" >&2; exit 2; }
[ -d "$ANAPATH" ]     || { echo "emit-cmake.sh: --anapath not a directory: $ANAPATH" >&2; exit 2; }
[ -d "$ENGINE_LIBS" ] || { echo "emit-cmake.sh: --engine-libs not a directory: $ENGINE_LIBS" >&2; exit 2; }

# Use absolute, forward-slash paths CMake accepts on every platform.
# On Windows (MSYS bash on GH runners), plain `pwd` returns `/c/...` which
# Windows cmake cannot resolve. `pwd -W` returns Windows-style `C:/...`.
if [ "${OS:-}" = "Windows_NT" ]; then
  ANAPATH=$(cd "$ANAPATH" && pwd -W)
  ENGINE_LIBS=$(cd "$ENGINE_LIBS" && pwd -W)
else
  ANAPATH=$(cd "$ANAPATH" && pwd)
  ENGINE_LIBS=$(cd "$ENGINE_LIBS" && pwd)
fi

if [ "$KB_ONLY" = "true" ]; then
  SRC_GLOB="\"$ANAPATH/kb/*.cpp\""
  SRC_SCOPE="kb/"
else
  SRC_GLOB="\"$ANAPATH/run/*.cpp\" \"$ANAPATH/kb/*.cpp\""
  SRC_SCOPE="run/ or kb/"
fi

# Build include + lib block contents.
# nlpengine-compile-libs zip layout (per .github/workflows/build-*.yml in nlp-engine):
#   include/Api/...   ← engine public API
#   include/cs/...    ← engine internal headers used by generated code
#   lib/lib{prim,kbm,consh,words,lite}.{a|lib}
#   lib/libicu*.{a|lib}   (linux/mac; windows uses .lib import libs separately)
INCLUDE_LINES=""
for d in "$ENGINE_LIBS/include/Api" "$ENGINE_LIBS/include/cs" "$ENGINE_LIBS/include"; do
  if [ -d "$d" ]; then
    INCLUDE_LINES="${INCLUDE_LINES}    \"$d\""$'\n'
  fi
done

ENGINE_LIB_LINES=""
ICU_LIB_LINES=""
if [ -d "$ENGINE_LIBS/lib" ]; then
  while IFS= read -r -d '' lib; do
    base=$(basename "$lib")
    # ICU static libs (libicu*.a on Linux/macOS, icu*.lib on Windows) must be
    # force-linked into the .so/.dylib so the typeinfo / vtable symbols
    # generated by virtual ICU classes (e.g. icu::ByteSink) are pulled in
    # even when no analyzer-side .o references them directly. Without this,
    # the .so loads with `undefined symbol: _ZTIN6icu_788ByteSinkE` at
    # runtime — the engine binary doesn't export its statically-linked ICU
    # so the .so has nowhere to resolve the symbol from.
    case "$base" in
      libicu*|icu*.lib)
        ICU_LIB_LINES="${ICU_LIB_LINES}    \"$lib\""$'\n'
        ;;
      *)
        ENGINE_LIB_LINES="${ENGINE_LIB_LINES}    \"$lib\""$'\n'
        ;;
    esac
  done < <(find "$ENGINE_LIBS/lib" -maxdepth 1 -type f \( -name '*.a' -o -name '*.lib' \) -print0 | sort -z)
fi

if [ -z "$ENGINE_LIB_LINES" ] && [ -z "$ICU_LIB_LINES" ]; then
  echo "emit-cmake.sh: no engine static libs found under $ENGINE_LIBS/lib" >&2
  exit 3
fi

OUT="$ANAPATH/CMakeLists.txt"

cat > "$OUT" <<EOF
cmake_minimum_required(VERSION 3.16)
project(nlp_generated_library LANGUAGES CXX)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_POSITION_INDEPENDENT_CODE ON)

set(ANALYZER_DIR "$ANAPATH")
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY "$ANAPATH")
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY "$ANAPATH")
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY "$ANAPATH")
foreach(OUTPUTCONFIG \${CMAKE_CONFIGURATION_TYPES})
    string(TOUPPER \${OUTPUTCONFIG} OUTPUTCONFIG_UPPER)
    set(CMAKE_LIBRARY_OUTPUT_DIRECTORY_\${OUTPUTCONFIG_UPPER} "$ANAPATH")
    set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_\${OUTPUTCONFIG_UPPER} "$ANAPATH")
    set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_\${OUTPUTCONFIG_UPPER} "$ANAPATH")
endforeach()

file(GLOB GENERATED_CPP $SRC_GLOB)
if(NOT GENERATED_CPP)
    message(FATAL_ERROR "No generated C++ sources found in $SRC_SCOPE.")
endif()

add_library(nlp_generated SHARED \${GENERATED_CPP})
# NLP-ENGINE-513: PREFIX "" suppresses the default "lib" that CMake adds to
# SHARED targets on Linux/macOS. Without it, the build produces
# libdate-time.so / libdate-time.dylib, but compile-analyzer.yml's
# `find -name "<analyzer>.so"` and the extension's runtime loader both
# expect the bare <analyzer>.so / .dylib (matching Windows's <analyzer>.dll).
set_target_properties(nlp_generated PROPERTIES OUTPUT_NAME "$ANALYZER" PREFIX "")

target_include_directories(nlp_generated PRIVATE
    "$ANAPATH"
    "$ANAPATH/run"
    "$ANAPATH/kb"
${INCLUDE_LINES})

set(NLP_ENGINE_LIBRARIES
${ENGINE_LIB_LINES})

set(NLP_ICU_LIBRARIES
${ICU_LIB_LINES})

target_link_libraries(nlp_generated PRIVATE \${NLP_ENGINE_LIBRARIES})

if(WIN32)
    # Windows ICU libs are import libs for icu*.dll — dynamic linkage, no
    # whole-archive needed.
    target_link_libraries(nlp_generated PRIVATE \${NLP_ICU_LIBRARIES})
elseif(APPLE)
    # macOS ld uses per-archive -force_load (no group wrapper).
    foreach(icu_lib \${NLP_ICU_LIBRARIES})
        target_link_libraries(nlp_generated PRIVATE "-Wl,-force_load,\${icu_lib}")
    endforeach()
else()
    # GNU ld / lld: --whole-archive ... --no-whole-archive around the ICU
    # static archives so virtual-class typeinfo (icu::ByteSink etc.) is
    # always emitted into the .so, regardless of whether analyzer code
    # references it directly.
    target_link_libraries(nlp_generated PRIVATE
        "-Wl,--whole-archive"
        \${NLP_ICU_LIBRARIES}
        "-Wl,--no-whole-archive")
endif()

if(WIN32)
    target_compile_definitions(nlp_generated PRIVATE _CRT_SECURE_NO_WARNINGS)
    if(MSVC)
        target_compile_options(nlp_generated PRIVATE /wd4005 /FI"StdAfx.h")
    endif()
else()
    # NLP-ENGINE-513: define LINUX so the engine's public headers take the
    # Linux/macOS branches that polyfill <tchar.h> and skip the Windows DLL
    # macros. Without this:
    #   - include/Api/libStream.h leaves LIBSTREAM_API expanding to
    #     __declspec(dllimport), which gcc rejects ("expected initializer
    #     before 'CLibStream'").
    #   - include/Api/my_tchar.h's '#define _TCHAR char' is gated on
    #     '#ifdef LINUX', so any generated source that uses _TCHAR fails.
    # Mirrors the per-subdir add_definitions(-DLINUX) the engine itself
    # uses in cs/libprim, cs/libconsh, lite, etc.
    target_compile_definitions(nlp_generated PRIVATE LINUX)
    target_compile_options(nlp_generated PRIVATE -include StdAfx.h)
    find_library(DL_LIBRARY dl)
    if(DL_LIBRARY)
        target_link_libraries(nlp_generated PRIVATE \${DL_LIBRARY})
    endif()
endif()
EOF

echo "emit-cmake.sh: wrote $OUT"
