#!/usr/bin/env python3
"""
Parse a CMake/compiler build log into the structured errors[] array
defined in the compile-service manifest schema.

For each error/warning the parser emits {file, line, column?, severity,
message}. The engine's `-COMPILE` step emits two kinds of provenance:

- file anchor (once per pass): `// nlp-source-file: <path>` on its own
  line near the top of every generated pass{N}.cpp
- per-rule anchor (one per rule): `/* nlp-source: <line> */` embedded
  inline inside the rule's switch-case body

The per-rule comment is C-style (block) rather than `//` because the
engine's Gen::nl is a no-op in release builds, so the whole pass
function body is emitted on one physical line — a `//` would swallow
the rest of the line including the closing brace. (This is the fix
introduced in NLP-ENGINE-488; older engines emitted `//`.)

The parser searches the error's own line first for the closest
preceding `/* nlp-source: ... */` (within-line), then falls back to
walking earlier lines for older-format `// nlp-source: ...` anchors so
errors generated by pre-488 engines still get mapped.

Compilers covered:
  GCC/Clang   path/file.cpp:LINE:COL: severity: message
              path/file.cpp:LINE: severity: message
  MSVC        path\\file.cpp(LINE,COL): severity CODE: message
              path\\file.cpp(LINE): severity CODE: message

Usage:
  python3 parse-errors.py --log <buildlog> --anapath <dir> --out <json>
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from typing import Optional

GCC_RE = re.compile(
    r"^(?P<file>[^:\n][^:\n]*\.(?:cpp|cc|cxx|h|hpp))"
    r":(?P<line>\d+)(?::(?P<col>\d+))?"
    r":\s*(?P<sev>error|warning|fatal error|note)"
    r":\s*(?P<msg>.+)$",
    re.IGNORECASE,
)

MSVC_RE = re.compile(
    r"^(?P<file>[A-Za-z]:\\[^\(]+?|[^\(]+?\\[^\(]+?\.(?:cpp|cc|cxx|h|hpp))"
    r"\((?P<line>\d+)(?:,(?P<col>\d+))?\)"
    r"\s*:\s*(?P<sev>error|warning|fatal error)"
    r"\s+[A-Z]+\d+\s*:\s*(?P<msg>.+)$",
    re.IGNORECASE,
)

# Per-construct anchor (NLP-ENGINE-488+): inline C-style comment that can appear
# anywhere within a line of generated code.
PROVENANCE_BLOCK_RE = re.compile(r"/\*\s*nlp-source:\s*(?P<line>\d+)\s*\*/")
# Legacy per-construct anchor (pre-488): own-line `//` comment.
PROVENANCE_SLASHSLASH_RE = re.compile(r"^\s*//\s*nlp-source:\s*(?P<line>\d+)\s*$")
# File anchor — emitted once at the top of each generated pass{N}.cpp.
PROVENANCE_FILE_RE = re.compile(r"^\s*//\s*nlp-source-file:\s*(?P<file>.+?)\s*$")


def find_provenance(
    cpp_path: str,
    error_line: int,
    error_column: Optional[int],
    anapath: str,
) -> Optional[tuple[str, int]]:
    """Map a compiler error location back to the originating .nlp source.

    Strategy:
    1. On the error line itself, find the LAST `/* nlp-source: <N> */` that
       starts before `error_column`. This is the common case after
       NLP-ENGINE-488: the whole switch is on one physical line and every
       case carries an inline block comment.
    2. If nothing on the error line, walk earlier lines for any inline block
       comment, then earlier still for a legacy `// nlp-source: <N>` line.
    3. Walk earlier lines for the `// nlp-source-file: <path>` anchor.

    Returns (relpath, line) with the path made relative to `anapath` when
    possible; None if either piece is missing.
    """
    try:
        with open(cpp_path, "r", encoding="utf-8", errors="replace") as f:
            lines = f.readlines()
    except OSError:
        return None

    upper = min(error_line, len(lines))
    found_line: Optional[int] = None

    # 1. Within-line search on the error line itself, last block-comment match
    #    whose start is before error_column (1-based → 0-based).
    if 0 < error_line <= len(lines):
        line_text = lines[error_line - 1]
        cutoff = (error_column - 1) if error_column else len(line_text)
        last_match = None
        for m in PROVENANCE_BLOCK_RE.finditer(line_text):
            if m.start() < cutoff:
                last_match = m
            else:
                break
        if last_match:
            found_line = int(last_match.group("line"))

    # 2. Fallback: scan earlier lines for any block or legacy comment.
    if found_line is None:
        for i in range(upper - 2, -1, -1):
            blocks = list(PROVENANCE_BLOCK_RE.finditer(lines[i]))
            if blocks:
                found_line = int(blocks[-1].group("line"))
                break
            m = PROVENANCE_SLASHSLASH_RE.match(lines[i])
            if m:
                found_line = int(m.group("line"))
                break

    # 3. File anchor: walk earlier lines for `// nlp-source-file:`.
    found_file: Optional[str] = None
    for i in range(upper - 1, -1, -1):
        m = PROVENANCE_FILE_RE.match(lines[i])
        if m:
            found_file = m.group("file").strip()
            break

    if found_line is None or found_file is None:
        return None

    # Normalize: convert backslashes (Windows engine output) and try to make
    # the path relative to anapath so the extension can map it to a workspace file.
    norm = found_file.replace("\\", "/")
    if os.path.isabs(norm):
        try:
            norm = os.path.relpath(norm, anapath).replace("\\", "/")
        except ValueError:
            pass  # different drive on Windows; keep absolute
    return norm, found_line


def normalize_severity(raw: str) -> str:
    raw = raw.lower()
    if "warning" in raw:
        return "warning"
    if "note" in raw:
        return "note"
    return "error"


def parse_log(log_path: str, anapath: str) -> list[dict]:
    errors: list[dict] = []
    with open(log_path, "r", encoding="utf-8", errors="replace") as f:
        for raw in f:
            line = raw.rstrip("\r\n")
            m = GCC_RE.match(line) or MSVC_RE.match(line)
            if not m:
                continue

            file_ref = m.group("file").strip()
            file_abs = file_ref if os.path.isabs(file_ref) else os.path.join(anapath, file_ref)

            entry: dict = {
                "file": os.path.relpath(file_abs, anapath) if os.path.exists(file_abs) else file_ref,
                "line": int(m.group("line")),
                "severity": normalize_severity(m.group("sev")),
                "message": m.group("msg").strip(),
            }
            if m.group("col"):
                entry["column"] = int(m.group("col"))

            col_val = int(m.group("col")) if m.group("col") else None
            prov = find_provenance(file_abs, int(m.group("line")), col_val, anapath)
            if prov:
                entry["nlpSourceFile"] = prov[0]
                entry["nlpSourceLine"] = prov[1]

            errors.append(entry)
    return errors


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--log", required=True)
    ap.add_argument("--anapath", required=True)
    ap.add_argument("--out", required=True)
    args = ap.parse_args()

    if not os.path.exists(args.log):
        print(f"parse-errors.py: log not found: {args.log}", file=sys.stderr)
        return 2

    errors = parse_log(args.log, args.anapath)
    with open(args.out, "w", encoding="utf-8") as f:
        json.dump(errors, f, indent=2)
    print(f"parse-errors.py: wrote {len(errors)} entries to {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
